### ISSUE TITLE
编码方式

### ISSUE THREAD

**Issue by G4419** [cgbcgb/A-LOAM-NOTED#1]
这些注释是什么编码方式？我用utf-8和bgk打开都会乱码

**Comment by QianYuan1437** [comment]
这个是GB2312编码格式，你需要选择更新编码格式后打开，搜索GB并选择就好了，这个问题确实不太方便，希望作者可以修复一下，谢谢

**Comment by QianYuan1437** [comment]
我针对这个问题以及UBUNTU20.04系统作了适配修改，详见我的fork链接，branch选择我的ubuntu20.04 mods即可：
https://github.com/QianYuan1437/A-LOAM-NOTED.git
希望对你有帮助 @G4419

**Comment by G4419** [comment]
好的 谢谢
